import type { WikiSceneId } from "./wikiScenes";

export type WikiTopicId =
  | "turn-flow"
  | "mana"
  | "action-points"
  | "cards-and-priority"
  | "combat"
  | "buildings"
  | "deck-rules";

export type WikiTopic = {
  id: WikiTopicId;
  title: string;
  summary: string;
  keyRules: string[];
  example: string;
  commonMistakes: string[];
  relatedTopicIds: WikiTopicId[];
  sceneId: WikiSceneId;
};

export const WIKI_TOPICS = [
  {
    id: "turn-flow",
    title: "Turn Flow",
    summary:
      "Turns alternate between sides, with each active side refreshing resources, spending actions, and passing control when finished.",
    keyRules: [
      "A match alternates sides through turns and rounds.",
      "The active side spends actions during its turn.",
      "Starting a turn refreshes Mana from the Hero and occupied Mana sources.",
      "Starting a turn refreshes Hero action points and Unit action points.",
      "The active side moves first, then attacks or skips attacks, then plays cards.",
      "Damaged surviving Units refresh Unit armor at the beginning of their owner's turn.",
      "A side draws at the start of later turns, not on its very first turn.",
      "Ending a turn is available after reaching Card Play.",
    ],
    example:
      "You spend actions, end turn, the opponent acts, then the next round begins when control returns to you.",
    commonMistakes: [
      "Expecting Units to keep damage forever.",
      "Expecting to draw on the first turn.",
      "Confusing round number with the active side's turn.",
    ],
    relatedTopicIds: ["mana", "action-points", "cards-and-priority"],
    sceneId: "turn-flow-refresh",
  },
  {
    id: "mana",
    title: "Mana",
    summary:
      "Mana pays for cards and refreshes at the start of your turn from your Hero plus occupied Mana sources.",
    keyRules: [
      "Mana pays for cards.",
      "At the start of your turn, Mana is replaced by a fresh amount.",
      "Base Mana comes from the Hero, and the current base value is 3 Mana.",
      "Occupied Mana sources add to turn-start Mana.",
      "Unspent Mana can matter during reaction windows before your next own-turn refresh.",
      "Mana is not generated by controlling ordinary Hexes.",
    ],
    example:
      "If your Hero provides 3 base Mana and you occupy a Mana Well, your next turn starts with extra Mana.",
    commonMistakes: [
      "Treating any occupied Hex as a Mana source.",
      "Thinking unused Mana permanently accumulates.",
      "Forgetting that a Mana source must be occupied.",
    ],
    relatedTopicIds: ["turn-flow", "buildings", "cards-and-priority"],
    sceneId: "mana-source",
  },
  {
    id: "action-points",
    title: "Action Points",
    summary:
      "Hero action points and Unit action points are separate per-turn budgets for movement, attacks, and activations.",
    keyRules: [
      "Hero action points pay for Hero movement and Hero attacks.",
      "Unit action points pay for Unit movement and Unit attacks.",
      "Moving one adjacent Hex costs one action point from the moving piece.",
      "Playing cards costs Mana, not action points.",
      "Activating a Building costs one action point from the occupying Hero or Unit.",
      "A piece with no action points cannot take action.",
      "Attack is limited to once per piece per turn, even if action points remain.",
      "Newly summoned Units enter with partial current Unit action points rather than a full turn's budget.",
    ],
    example:
      "A Hero with 3 action points can move and attack while still saving Mana for card play after attacks.",
    commonMistakes: [
      "Spending Unit action points to play cards.",
      "Expecting a Unit to attack twice in one turn.",
      "Forgetting Building activation spends the occupant's action point.",
    ],
    relatedTopicIds: ["turn-flow", "combat", "buildings", "cards-and-priority"],
    sceneId: "action-points-budget",
  },
  {
    id: "cards-and-priority",
    title: "Cards and Priority",
    summary:
      "Cards spend Mana, then enter the stack so priority can decide whether responses happen first.",
    keyRules: [
      "Playing a card spends Mana and no action points.",
      "Unit cards create Units on adjacent empty Hexes.",
      "Spell cards create immediate effects from the caster Hero when they resolve.",
      "Item cards equip friendly Units.",
      "Building cards create neutral Buildings on adjacent empty Hexes.",
      "Actions are placed on the stack before resolving.",
      "When a side has priority, it may respond with a legal higher-priority Spell or pass.",
      "When both sides are done adding responses, stack items resolve from the top.",
    ],
    example:
      "You cast a Spell, the opponent gets priority, they may answer, then priority passing lets the top stack item resolve first.",
    commonMistakes: [
      "Expecting every card to resolve immediately.",
      "Trying to summon Units away from the Hero.",
      "Trying to target friendly pieces with damage Spells or enemies with healing or buff Spells.",
    ],
    relatedTopicIds: ["mana", "action-points", "combat", "buildings"],
    sceneId: "cards-priority-stack",
  },
  {
    id: "combat",
    title: "Combat",
    summary:
      "Heroes and Units attack enemy pieces in range, with counterdamage only when the defender's own range reaches back.",
    keyRules: [
      "A Hero or Unit attacks enemy pieces within its attack range.",
      "Range is measured by hex distance.",
      "Range 1 means adjacent combat.",
      "Attack range has no blocker, line-of-sight, or straight-line requirement.",
      "The attacker deals its attack value to the target.",
      "The target only counterdamages if its own attack range reaches the attacker.",
      "Hero damage lowers HP after Hero shield is consumed.",
      "Unit damage lowers Unit armor.",
      "The match ends when a Hero reaches 0 HP or below.",
      "If both Heroes are reduced to 0 HP at the same time, Player wins under current rules.",
    ],
    example:
      "An Archer can attack from range 2. A range-1 Unit does not counterattack unless the Archer is adjacent.",
    commonMistakes: [
      "Assuming every attack causes counterdamage.",
      "Assuming line of sight blocks ranged attacks.",
      "Calling Unit armor health.",
    ],
    relatedTopicIds: ["action-points", "turn-flow", "cards-and-priority"],
    sceneId: "combat-range-counter",
  },
  {
    id: "buildings",
    title: "Buildings",
    summary:
      "Buildings are neutral board features that can provide Mana, auras, or activated effects to whichever side occupies them.",
    keyRules: [
      "Buildings are neutral, permanent board features on Hexes.",
      "A Building can be occupied by either side.",
      "Buildings are not owned, captured, or destroyed in v1.",
      "Building cards create Buildings on adjacent empty Hexes.",
      "A Mana Well is a Building that grants turn-start Mana while occupied.",
      "Some Buildings provide aura effects while occupied.",
      "Some Buildings have activated effects.",
      "Activated Buildings can be used once per turn and spend one action point from the occupying Hero or Unit.",
      "Building activations go on the stack.",
    ],
    example:
      "If your Unit stands on a Mana Well when your turn starts, that Mana Well increases your refreshed Mana.",
    commonMistakes: [
      "Treating a Building as controlled forever after building it.",
      "Trying to place a Building on an occupied Hex.",
      "Expecting a Building to block occupation like a piece.",
    ],
    relatedTopicIds: ["mana", "action-points", "cards-and-priority"],
    sceneId: "building-occupation",
  },
  {
    id: "deck-rules",
    title: "Deck Rules",
    summary:
      "Deck recipes are saved pre-match card lists, and only Legal deck recipes can be used to start matches.",
    keyRules: [
      "Deck recipes are pre-match card lists.",
      "Legal deck recipes can be used to start matches.",
      "Draft deck recipes are saved but not legal for match start.",
      "Deck recipes use rarity-based copy limits.",
      "Minimum cards: 60.",
      "Basic card copy limit: 5.",
      "Advanced card copy limit: 4.",
      "Rare card copy limit: 3.",
      "Advanced card total limit: 24.",
      "Rare card total limit: 12.",
      "A match loadout combines Hero, deck recipe or system deck recipe, and rune loadout.",
    ],
    example:
      "A deck recipe with too few cards or too many Rare cards remains a Draft deck recipe until fixed.",
    commonMistakes: [
      "Calling a Deck recipe just a deck in rule copy.",
      "Assuming every saved Deck recipe can start a match.",
      "Using rarity names like common, uncommon, or legendary.",
    ],
    relatedTopicIds: ["cards-and-priority", "mana"],
    sceneId: "deck-recipe-legality",
  },
] satisfies WikiTopic[];

export function wikiTopicById(id: string): WikiTopic | null {
  return WIKI_TOPICS.find((topic) => topic.id === id) ?? null;
}
