use serde::Serialize;

use crate::deck_library::starter_recipe_count;
use crate::match_session::{
    BuffTargetPolicy, BuildingEffect, Card, CardKind, ItemActiveEffect, ItemPassiveEffect, Rarity,
    SpellEffect,
};

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogCard {
    pub id: String,
    pub template_id: String,
    pub name: String,
    pub rarity: Rarity,
    pub cost: u8,
    pub text: String,
    pub kind: CardKind,
    pub copy_count: u8,
    pub art_key: String,
    pub art_path: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogResponse {
    pub cards: Vec<CatalogCard>,
}

pub fn starter_catalog() -> Vec<CatalogCard> {
    starter_card_templates()
        .into_iter()
        .map(|card| {
            let copy_count = starter_recipe_count(&card.template_id)
                .try_into()
                .expect("starter recipe counts should fit in u8");
            let art_key = card.template_id.clone();
            CatalogCard {
                id: card.template_id.clone(),
                template_id: card.template_id,
                name: card.name,
                rarity: card.rarity,
                cost: card.cost,
                text: card.text,
                kind: card.kind,
                copy_count,
                art_path: format!("/card-art/{art_key}.svg"),
                art_key,
            }
        })
        .collect()
}

pub fn starter_card_templates() -> Vec<Card> {
    vec![
        unit_card(
            "ember-squire",
            "Ember Squire",
            Rarity::Basic,
            1,
            "1 attack / 2 armor / 2 AP.",
            UnitStats {
                attack: 1,
                armor: 2,
                max_ap: 2,
            },
        ),
        unit_card(
            "swift-familiar",
            "Swift Familiar",
            Rarity::Basic,
            1,
            "1 attack / 1 armor / 3 AP.",
            UnitStats {
                attack: 1,
                armor: 1,
                max_ap: 3,
            },
        ),
        unit_card(
            "stoneguard",
            "Stoneguard",
            Rarity::Basic,
            2,
            "1 attack / 4 armor / 2 AP.",
            UnitStats {
                attack: 1,
                armor: 4,
                max_ap: 2,
            },
        ),
        unit_card(
            "rune-bruiser",
            "Rune Bruiser",
            Rarity::Basic,
            2,
            "2 attack / 2 armor / 2 AP.",
            UnitStats {
                attack: 2,
                armor: 2,
                max_ap: 2,
            },
        ),
        unit_card(
            "blade-dancer",
            "Blade Dancer",
            Rarity::Advanced,
            3,
            "2 attack / 2 armor / 3 AP.",
            UnitStats {
                attack: 2,
                armor: 2,
                max_ap: 3,
            },
        ),
        unit_card(
            "shield-adept",
            "Shield Adept",
            Rarity::Advanced,
            3,
            "1 attack / 5 armor / 2 AP.",
            UnitStats {
                attack: 1,
                armor: 5,
                max_ap: 2,
            },
        ),
        spell_card(
            "quick-salve",
            "Quick Salve",
            Rarity::Basic,
            1,
            "Priority 2. Range 2. Heal 2 to an allied unit or hero.",
            2,
            2,
            SpellEffect::Heal { amount: 2 },
        ),
        spell_card(
            "spark-jolt",
            "Spark Jolt",
            Rarity::Basic,
            1,
            "Priority 3. Range 2. Deal 1 damage to an enemy unit or hero.",
            2,
            3,
            SpellEffect::Damage { amount: 1 },
        ),
        spell_card(
            "warding-sigil",
            "Warding Sigil",
            Rarity::Basic,
            1,
            "Priority 2. Range 2. An allied unit gains +1 armor.",
            2,
            2,
            SpellEffect::Buff {
                attack: 0,
                armor: 1,
            },
        ),
        item_card(
            "rune-charm",
            "Rune Charm",
            Rarity::Basic,
            1,
            "Range 2. Equip to an allied unit. Passive: +1 armor. Drops when the unit dies.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 1,
                max_ap: 0,
            },
            None,
        ),
        item_card_for_targets(
            "runekeeper-lens",
            "Runekeeper Lens",
            Rarity::Basic,
            1,
            "Range 2. Equip to an allied unit or hero. Active: spend 1 carrier AP to draw 1.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::Draw {
                amount: 1,
                priority: 2,
            }),
        ),
        item_card_for_targets(
            "emberbrand-charm",
            "Emberbrand Charm",
            Rarity::Basic,
            1,
            "Range 2. Equip to an allied unit or hero. Passive: +1 attack.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 0,
            },
            None,
        ),
        item_card_for_targets(
            "salve-kit",
            "Salve Kit",
            Rarity::Basic,
            1,
            "Range 2. Equip to an allied unit or hero. Active: spend 1 carrier AP to heal carrier 2.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 2,
            }),
        ),
        item_card_for_targets(
            "spark-needle",
            "Spark Needle",
            Rarity::Basic,
            2,
            "Range 2. Equip to an allied unit or hero. Active: spend 1 carrier AP to deal 1 damage within range 2.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::DamageTarget {
                amount: 1,
                range: 2,
                priority: 3,
            }),
        ),
        item_card(
            "warded-buckle",
            "Warded Buckle",
            Rarity::Basic,
            1,
            "Range 2. Equip to an allied unit. Passive: +1 armor.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 1,
                max_ap: 0,
            },
            None,
        ),
        item_card_for_targets(
            "scout-boots",
            "Scout Boots",
            Rarity::Basic,
            2,
            "Range 2. Equip to an allied unit or hero. Passive: +1 AP.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 1,
            },
            None,
        ),
        item_card_for_targets(
            "stone-totem",
            "Stone Totem",
            Rarity::Basic,
            2,
            "Range 2. Equip to an allied hero. Active: spend 1 carrier AP to add a +1 armor stat marker.",
            2,
            BuffTargetPolicy::HeroesOnly,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::StatMarker {
                attack: 0,
                armor: 1,
                max_ap: 0,
                priority: 2,
            }),
        ),
        unit_card(
            "rune-runner",
            "Rune Runner",
            Rarity::Basic,
            2,
            "1 attack / 1 armor / 4 AP.",
            UnitStats {
                attack: 1,
                armor: 1,
                max_ap: 4,
            },
        ),
        unit_card(
            "ash-hound",
            "Ash Hound",
            Rarity::Basic,
            2,
            "2 attack / 1 armor / 3 AP.",
            UnitStats {
                attack: 2,
                armor: 1,
                max_ap: 3,
            },
        ),
        unit_card(
            "ridge-berserker",
            "Ridge Berserker",
            Rarity::Basic,
            2,
            "3 attack / 1 armor / 2 AP.",
            UnitStats {
                attack: 3,
                armor: 1,
                max_ap: 2,
            },
        ),
        unit_card(
            "pathfinder",
            "Pathfinder",
            Rarity::Basic,
            2,
            "1 attack / 1 armor / 4 AP.",
            UnitStats {
                attack: 1,
                armor: 1,
                max_ap: 4,
            },
        ),
        unit_card(
            "field-mason",
            "Field Mason",
            Rarity::Basic,
            2,
            "1 attack / 3 armor / 2 AP.",
            UnitStats {
                attack: 1,
                armor: 3,
                max_ap: 2,
            },
        ),
        unit_card(
            "prism-initiate",
            "Prism Initiate",
            Rarity::Basic,
            1,
            "1 attack / 3 armor / 1 AP.",
            UnitStats {
                attack: 1,
                armor: 3,
                max_ap: 1,
            },
        ),
        building_card(
            "mana-well",
            "Mana Well",
            Rarity::Basic,
            2,
            "Build on an adjacent empty hex. Occupying side gains +1 mana at the start of its turn.",
            BuildingEffect::TurnStartMana { amount: 1 },
        ),
        spell_card(
            "runic-insight",
            "Runic Insight",
            Rarity::Basic,
            1,
            "Priority 1. Range 0. Draw 1 card.",
            0,
            1,
            SpellEffect::Draw { amount: 1 },
        ),
        spell_card(
            "mending-rune",
            "Mending Rune",
            Rarity::Advanced,
            2,
            "Priority 2. Range 2. Heal 3 to an allied unit or hero.",
            2,
            2,
            SpellEffect::Heal { amount: 3 },
        ),
        spell_card(
            "war-chant",
            "War Chant",
            Rarity::Advanced,
            3,
            "Priority 1. Range 2. An allied unit gains +1 attack and +1 armor.",
            2,
            1,
            SpellEffect::Buff {
                attack: 1,
                armor: 1,
            },
        ),
        spell_card(
            "crushing-roar",
            "Crushing Roar",
            Rarity::Advanced,
            3,
            "Priority 1. Range 2. An allied unit gains +2 attack.",
            2,
            1,
            SpellEffect::Buff {
                attack: 2,
                armor: 0,
            },
        ),
        spell_card(
            "ember-lance",
            "Ember Lance",
            Rarity::Advanced,
            3,
            "Priority 3. Range 3. Deal 2 damage to an enemy unit or hero.",
            3,
            3,
            SpellEffect::Damage { amount: 2 },
        ),
        spell_card(
            "arcane-parry",
            "Arcane Parry",
            Rarity::Advanced,
            2,
            "Priority 4. Range 2. An allied unit gains +2 armor.",
            2,
            4,
            SpellEffect::Buff {
                attack: 0,
                armor: 2,
            },
        ),
        spell_card(
            "starlit-study",
            "Starlit Study",
            Rarity::Advanced,
            2,
            "Priority 2. Range 0. Draw 2 cards.",
            0,
            2,
            SpellEffect::Draw { amount: 2 },
        ),
        item_card(
            "ember-flask",
            "Ember Flask",
            Rarity::Advanced,
            2,
            "Range 2. Equip to an allied unit. Passive: +1 attack. Active: spend 1 unit AP to heal carrier 2.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 0,
            }),
        ),
        item_card_for_targets(
            "pyre-brand",
            "Pyre Brand",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit or hero. Passive: +1 attack. Active: spend 1 carrier AP to deal 2 damage within range 2.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::DamageTarget {
                amount: 2,
                range: 2,
                priority: 3,
            }),
        ),
        item_card_for_targets(
            "chrono-cog",
            "Chrono Cog",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit or hero. Passive: +1 AP. Active: spend 1 carrier AP to draw 1.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 1,
            },
            Some(ItemActiveEffect::Draw {
                amount: 1,
                priority: 4,
            }),
        ),
        spell_card(
            "cinder-ring",
            "Cinder Ring",
            Rarity::Advanced,
            3,
            "Priority 2. Range 3. Deal 1 damage to an enemy and adjacent enemies.",
            3,
            2,
            SpellEffect::AreaDamage {
                amount: 1,
                radius: 1,
            },
        ),
        spell_card(
            "prism-ray",
            "Prism Ray",
            Rarity::Advanced,
            3,
            "Priority 3. Range 3. Deal 2 damage to enemies in a straight line.",
            3,
            3,
            SpellEffect::LineDamage { amount: 2 },
        ),
        spell_card(
            "piercing-volley",
            "Piercing Volley",
            Rarity::Advanced,
            3,
            "Priority 3. Range 3. Deal 2 damage to enemies in a straight line.",
            3,
            3,
            SpellEffect::LineDamage { amount: 2 },
        ),
        unit_card(
            "glass-duelist",
            "Glass Duelist",
            Rarity::Advanced,
            2,
            "3 attack / 1 armor / 2 AP.",
            UnitStats {
                attack: 3,
                armor: 1,
                max_ap: 2,
            },
        ),
        unit_card(
            "flame-weaver",
            "Flame Weaver",
            Rarity::Advanced,
            4,
            "3 attack / 2 armor / 2 AP.",
            UnitStats {
                attack: 3,
                armor: 2,
                max_ap: 2,
            },
        ),
        spell_card(
            "bastion-rune",
            "Bastion Rune",
            Rarity::Advanced,
            4,
            "Priority 1. Range 2. An allied unit gains +4 armor.",
            2,
            1,
            SpellEffect::Buff {
                attack: 0,
                armor: 4,
            },
        ),
        spell_card(
            "fortify-position",
            "Fortify Position",
            Rarity::Advanced,
            3,
            "Priority 2. Range 2. An allied unit gains +3 armor.",
            2,
            2,
            SpellEffect::Buff {
                attack: 0,
                armor: 3,
            },
        ),
        spell_card(
            "temporal-bolt",
            "Temporal Bolt",
            Rarity::Advanced,
            3,
            "Priority 5. Range 2. Deal 2 damage to an enemy unit or hero.",
            2,
            5,
            SpellEffect::Damage { amount: 2 },
        ),
        unit_card(
            "iron-colossus",
            "Iron Colossus",
            Rarity::Rare,
            6,
            "4 attack / 6 armor / 1 AP.",
            UnitStats {
                attack: 4,
                armor: 6,
                max_ap: 1,
            },
        ),
        spell_card(
            "meteor-bloom",
            "Meteor Bloom",
            Rarity::Rare,
            5,
            "Priority 2. Range 3. Deal 2 damage to an enemy and adjacent enemies.",
            3,
            2,
            SpellEffect::AreaDamage {
                amount: 2,
                radius: 1,
            },
        ),
        spell_card(
            "thunder-rail",
            "Thunder Rail",
            Rarity::Rare,
            5,
            "Priority 4. Range 3. Deal 3 damage to enemies in a straight line.",
            3,
            4,
            SpellEffect::LineDamage { amount: 3 },
        ),
        spell_card(
            "starfire-bolt",
            "Starfire Bolt",
            Rarity::Rare,
            5,
            "Priority 3. Range 3. Deal 4 damage to an enemy unit or hero.",
            3,
            3,
            SpellEffect::Damage { amount: 4 },
        ),
        spell_card(
            "eclipse-strike",
            "Eclipse Strike",
            Rarity::Rare,
            4,
            "Priority 5. Range 3. Deal 3 damage to an enemy unit or hero.",
            3,
            5,
            SpellEffect::Damage { amount: 3 },
        ),
        spell_card(
            "deadeye-mark",
            "Deadeye Mark",
            Rarity::Rare,
            4,
            "Priority 5. Range 3. Deal 3 damage to an enemy unit or hero.",
            3,
            5,
            SpellEffect::Damage { amount: 3 },
        ),
        item_card(
            "breaker-axe",
            "Breaker Axe",
            Rarity::Rare,
            4,
            "Range 2. Equip to an allied unit. Passive: +2 attack. Drops when the unit dies.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 2,
                armor: 0,
                max_ap: 0,
            },
            None,
        ),
        item_card(
            "clockwork-rig",
            "Clockwork Rig",
            Rarity::Rare,
            4,
            "Range 2. Equip to an allied unit. Passive: +1 armor, +1 AP. Active: spend 1 unit AP to heal carrier 2.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 1,
                max_ap: 1,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 0,
            }),
        ),
        item_card(
            "titan-plate",
            "Titan Plate",
            Rarity::Rare,
            4,
            "Range 2. Equip to an allied unit. Passive: +4 armor. Drops when the unit dies.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 4,
                max_ap: 0,
            },
            None,
        ),
        item_card(
            "overclock-bracers",
            "Overclock Bracers",
            Rarity::Rare,
            4,
            "Range 2. Equip to an allied unit. Passive: +1 attack, +2 AP. Active: spend 1 unit AP to heal carrier 2.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 2,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 0,
            }),
        ),
        item_card(
            "sunforged-halberd",
            "Sunforged Halberd",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit. Passive: +2 attack, +1 armor. Drops when the unit dies.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 2,
                armor: 1,
                max_ap: 0,
            },
            None,
        ),
        item_card(
            "guardian-harness",
            "Guardian Harness",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit. Passive: +2 armor, +1 AP. Active: spend 1 unit AP to heal carrier 3.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 2,
                max_ap: 1,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 3,
                priority: 0,
            }),
        ),
        item_card(
            "rift-gauntlet",
            "Rift Gauntlet",
            Rarity::Rare,
            5,
            "Range 2. Equip to an allied unit. Passive: +3 attack. Active: spend 1 unit AP to heal carrier 2.",
            2,
            ItemPassiveEffect::StatBonus {
                attack: 3,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 0,
            }),
        ),
        item_card_for_targets(
            "warden-plate",
            "Warden Plate",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit or hero. Passive: +1 armor. Active: spend 1 carrier AP to heal carrier 2.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 1,
                max_ap: 0,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 2,
                priority: 2,
            }),
        ),
        item_card_for_targets(
            "battle-standard",
            "Battle Standard",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit or hero. Active: spend 1 carrier AP to add a +1 attack stat marker.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::StatMarker {
                attack: 1,
                armor: 0,
                max_ap: 0,
                priority: 1,
            }),
        ),
        item_card_for_targets(
            "hunter-scope",
            "Hunter Scope",
            Rarity::Advanced,
            3,
            "Range 2. Equip to an allied unit or hero. Passive: +1 attack. Active: spend 1 carrier AP to deal 2 damage within range 3.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::DamageTarget {
                amount: 2,
                range: 3,
                priority: 4,
            }),
        ),
        item_card_for_targets(
            "builder-toolkit",
            "Builder Toolkit",
            Rarity::Advanced,
            2,
            "Range 2. Equip to an allied unit or hero. Passive: +1 armor. Active: spend 1 carrier AP to draw 1.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 1,
                max_ap: 0,
            },
            Some(ItemActiveEffect::Draw {
                amount: 1,
                priority: 1,
            }),
        ),
        item_card_for_targets(
            "starcore-engine",
            "Starcore Engine",
            Rarity::Rare,
            5,
            "Range 2. Equip to an allied unit or hero. Passive: +1 attack, +1 AP. Active: spend 1 carrier AP to draw 2.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 1,
                armor: 0,
                max_ap: 1,
            },
            Some(ItemActiveEffect::Draw {
                amount: 2,
                priority: 2,
            }),
        ),
        item_card_for_targets(
            "titan-aegis",
            "Titan Aegis",
            Rarity::Rare,
            4,
            "Range 2. Equip to an allied unit or hero. Passive: +3 armor. Active: spend 1 carrier AP to heal carrier 3.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 0,
                armor: 3,
                max_ap: 0,
            },
            Some(ItemActiveEffect::HealCarrier {
                amount: 3,
                priority: 4,
            }),
        ),
        item_card_for_targets(
            "rift-crown",
            "Rift Crown",
            Rarity::Rare,
            5,
            "Range 2. Equip to an allied unit or hero. Passive: +2 attack. Active: spend 1 carrier AP to deal 3 damage within range 3.",
            2,
            BuffTargetPolicy::UnitsAndHeroes,
            ItemPassiveEffect::StatBonus {
                attack: 2,
                armor: 0,
                max_ap: 0,
            },
            Some(ItemActiveEffect::DamageTarget {
                amount: 3,
                range: 3,
                priority: 5,
            }),
        ),
        building_card(
            "stone-bastion",
            "Stone Bastion",
            Rarity::Advanced,
            3,
            "Build on an adjacent empty hex. While occupied, allied units within range 1 gain +1 armor.",
            BuildingEffect::AuraStatBonus {
                range: 1,
                targets: BuffTargetPolicy::UnitsOnly,
                attack: 0,
                armor: 1,
                max_ap: 0,
            },
        ),
        building_card(
            "watchtower",
            "Watchtower",
            Rarity::Advanced,
            3,
            "Build on an adjacent empty hex. Activate: occupant spends 1 AP to deal 2 damage along the best enemy line within range 2.",
            BuildingEffect::ActivatedDamageLine {
                range: 2,
                amount: 2,
            },
        ),
        building_card(
            "war-foundry",
            "War Foundry",
            Rarity::Rare,
            4,
            "Build on an adjacent empty hex. While occupied, allied units within range 1 gain +1 attack.",
            BuildingEffect::AuraStatBonus {
                range: 1,
                targets: BuffTargetPolicy::UnitsOnly,
                attack: 1,
                armor: 0,
                max_ap: 0,
            },
        ),
        building_card(
            "healing-font",
            "Healing Font",
            Rarity::Advanced,
            3,
            "Build on an adjacent empty hex. Activate: occupant spends 1 AP to heal an allied hero or unit within range 2 for 3.",
            BuildingEffect::ActivatedHeal {
                range: 2,
                amount: 3,
                targets: BuffTargetPolicy::UnitsAndHeroes,
            },
        ),
        unit_card(
            "phoenix-adept",
            "Phoenix Adept",
            Rarity::Rare,
            5,
            "3 attack / 3 armor / 3 AP.",
            UnitStats {
                attack: 3,
                armor: 3,
                max_ap: 3,
            },
        ),
        unit_card(
            "vanguard-golem",
            "Vanguard Golem",
            Rarity::Rare,
            4,
            "2 attack / 5 armor / 2 AP.",
            UnitStats {
                attack: 2,
                armor: 5,
                max_ap: 2,
            },
        ),
        unit_card(
            "relic-bearer",
            "Relic Bearer",
            Rarity::Basic,
            2,
            "1 attack / 2 armor / 3 AP.",
            UnitStats {
                attack: 1,
                armor: 2,
                max_ap: 3,
            },
        ),
        unit_card(
            "banner-guard",
            "Banner Guard",
            Rarity::Advanced,
            3,
            "1 attack / 4 armor / 2 AP.",
            UnitStats {
                attack: 1,
                armor: 4,
                max_ap: 2,
            },
        ),
        unit_card(
            "vault-runner",
            "Vault Runner",
            Rarity::Advanced,
            3,
            "2 attack / 2 armor / 4 AP.",
            UnitStats {
                attack: 2,
                armor: 2,
                max_ap: 4,
            },
        ),
        unit_card(
            "armory-colossus",
            "Armory Colossus",
            Rarity::Rare,
            5,
            "3 attack / 5 armor / 2 AP.",
            UnitStats {
                attack: 3,
                armor: 5,
                max_ap: 2,
            },
        ),
        spell_card(
            "armory-survey",
            "Armory Survey",
            Rarity::Basic,
            1,
            "Priority 1. Range 0. Draw 1 card.",
            0,
            1,
            SpellEffect::Draw { amount: 1 },
        ),
        spell_card(
            "reforge",
            "Reforge",
            Rarity::Advanced,
            2,
            "Priority 2. Range 2. An allied unit gains +1 attack and +1 armor, or an allied hero gains +1 attack and +1 shield.",
            2,
            2,
            SpellEffect::StatBuff {
                attack: 1,
                armor: 1,
                max_ap: 0,
                targets: BuffTargetPolicy::UnitsAndHeroes,
            },
        ),
        spell_card(
            "overload-spark",
            "Overload Spark",
            Rarity::Advanced,
            2,
            "Priority 4. Range 2. Deal 2 damage to an enemy unit or hero.",
            2,
            4,
            SpellEffect::Damage { amount: 2 },
        ),
        spell_card(
            "relic-storm",
            "Relic Storm",
            Rarity::Rare,
            5,
            "Priority 3. Range 3. Deal 2 damage to an enemy and adjacent enemies.",
            3,
            3,
            SpellEffect::AreaDamage {
                amount: 2,
                radius: 1,
            },
        ),
        spell_card(
            "comet-spear",
            "Comet Spear",
            Rarity::Rare,
            6,
            "Priority 3. Range 3. Deal 5 damage to an enemy unit or hero.",
            3,
            3,
            SpellEffect::Damage { amount: 5 },
        ),
        spell_card(
            "colossus-oath",
            "Colossus Oath",
            Rarity::Rare,
            5,
            "Priority 1. Range 2. An allied unit gains +2 attack and +3 armor, or an allied hero gains +2 attack and +3 shield.",
            2,
            1,
            SpellEffect::StatBuff {
                attack: 2,
                armor: 3,
                max_ap: 0,
                targets: BuffTargetPolicy::UnitsAndHeroes,
            },
        ),
        spell_card(
            "surge-protocol",
            "Surge Protocol",
            Rarity::Rare,
            4,
            "Priority 2. Range 2. An allied unit gains +2 attack, +1 armor, and +1 AP.",
            2,
            2,
            SpellEffect::StatBuff {
                attack: 2,
                armor: 1,
                max_ap: 1,
                targets: BuffTargetPolicy::UnitsOnly,
            },
        ),
    ]
}

pub fn card_template_by_id(template_id: &str) -> Option<Card> {
    starter_card_templates()
        .into_iter()
        .find(|card| card.template_id == template_id)
}

struct UnitStats {
    attack: i32,
    armor: i32,
    max_ap: u8,
}

fn unit_card(
    template_id: &str,
    name: &str,
    rarity: Rarity,
    cost: u8,
    text: &str,
    stats: UnitStats,
) -> Card {
    Card {
        id: template_id.to_string(),
        template_id: template_id.to_string(),
        name: name.to_string(),
        rarity,
        cost,
        text: text.to_string(),
        kind: CardKind::Unit {
            attack: stats.attack,
            armor: stats.armor,
            max_ap: stats.max_ap,
        },
    }
}

#[allow(
    clippy::too_many_arguments,
    reason = "card templates read clearly at call sites"
)]
fn spell_card(
    template_id: &str,
    name: &str,
    rarity: Rarity,
    cost: u8,
    text: &str,
    range: u8,
    priority: u8,
    effect: SpellEffect,
) -> Card {
    Card {
        id: template_id.to_string(),
        template_id: template_id.to_string(),
        name: name.to_string(),
        rarity,
        cost,
        text: text.to_string(),
        kind: CardKind::Spell {
            range,
            priority,
            effect,
        },
    }
}

#[allow(
    clippy::too_many_arguments,
    reason = "card templates read clearly at call sites"
)]
fn item_card(
    template_id: &str,
    name: &str,
    rarity: Rarity,
    cost: u8,
    text: &str,
    range: u8,
    passive: ItemPassiveEffect,
    active: Option<ItemActiveEffect>,
) -> Card {
    item_card_for_targets(
        template_id,
        name,
        rarity,
        cost,
        text,
        range,
        BuffTargetPolicy::UnitsOnly,
        passive,
        active,
    )
}

fn item_card_for_targets(
    template_id: &str,
    name: &str,
    rarity: Rarity,
    cost: u8,
    text: &str,
    range: u8,
    targets: BuffTargetPolicy,
    passive: ItemPassiveEffect,
    active: Option<ItemActiveEffect>,
) -> Card {
    Card {
        id: template_id.to_string(),
        template_id: template_id.to_string(),
        name: name.to_string(),
        rarity,
        cost,
        text: text.to_string(),
        kind: CardKind::Item {
            range,
            targets,
            passive,
            active,
        },
    }
}

fn building_card(
    template_id: &str,
    name: &str,
    rarity: Rarity,
    cost: u8,
    text: &str,
    effect: BuildingEffect,
) -> Card {
    Card {
        id: template_id.to_string(),
        template_id: template_id.to_string(),
        name: name.to_string(),
        rarity,
        cost,
        text: text.to_string(),
        kind: CardKind::Building { effect },
    }
}
